POST http://localhost:3000/api
Content-Type: application/json

{
    "first_name": "Elon"
}

###

GET http://localhost:3000/api

### Adding a product

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "product_id": 52345
}
### Adding a product

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "product_id": 2345
}

### Main Order

POST http://localhost:3000/api
Content-Type: application/json

{
    "first_name": "Elon",
    "last_name": "Musk",
    "phone_number": "(123) 456-1234",
    "product_id": 2345
}

### Bad Order (order does not exist)

POST http://localhost:3000/api
Content-Type: application/json

{
    "first_name": "Elon",
    "last_name": "Musk",
    "phone_number": "(123) 456-1234",
    "product_id": 12345
}

### Another order

POST http://localhost:3000/api
Content-Type: application/json

{
    "first_name": "Elon",
    "last_name": "Musk",
    "phone_number": "(123) 456-1234",
    "product_id": 52345
}

### Invalid Order

POST http://localhost:3000/api
Content-Type: application/json

{
    "first_name": "Elon",
    "last_name": "Musk",
    "phone_number": "(123) 456-1234",
    "product_id": "abc"
}

### Invalid Order 2

POST http://localhost:3000/api
Content-Type: application/json

{
    "first_name": "Elon",
    "last_name": "Musk",
    "phone_number": "(123) 456-1234",
    "product_id": "-- \" $find ;'"
}

### Invalid

POST http://localhost:3000/api
Content-Type: application/json

{
    "first_name": "Elon",
    "last_name": 12.6,
    "phone_number": "(123) 456-1234",
    "product_id": 2345,
    "extra": 1234
}
