POST http://localhost:3000/api
Content-Type: application/json

{
    "first_name": "Alan"
}

###

GET http://localhost:3000/api

### Adding a product

POSt http://localhost:3000/api/products
Content-Type: application/json

{
    "product_id": 2345
}
